#
# Print the build out of source message and terminate
# i.e. If a user gets here they did BAD !!!
#
message("")
message("===================================================================")
message("~~~~~~~~~~~~~~ In-source builds are not permitted ~~~~~~~~~~~~~~~~~")
message("===================================================================")
message("")
message("- INSTRUCTIONS -")
message("This library has been configured to prevent building within the")
message("source tree. You must build within a seperate directory to keep")
message("configurations seperate.  Follow these steps:")
message("")
message("1. Remove the cache files you just created.")
message("> rm -r CMakeCache.txt CMakeFiles")
message("")
message("2. Create and Change into a build directory.")
message("> mkdir location/of/mybuild")
message("> cd location/of/build")
message("")
message("3. Configure and Make your own installation.")
message("> cmake location/of/repo")
message("")
message("===================================================================")
message("")
message("PLEASE READ ABOVE MESSAGE & INSTRUCTIONS")
message("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
message("")
message(FATAL_ERROR)
